FROM node:18-alpine

WORKDIR /app

# Копируем только необходимое
COPY package.json yarn.lock ./
COPY dist/ ./dist/

# Ставим только production-зависимости
RUN yarn install --production

EXPOSE 8080
CMD ["node", "dist/main.js"]